routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Orchid\Platform\Http\Controllers\Systems\IndexController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');

//Posts
Route::get('posts', 'PostController@list')->name('posts.list');
//Route::get('posts/categories/{category}', 'PostController@category')->name('posts.category');
Route::get('posts/{post}', 'PostController@index')->name('post');

//Request
Route::post('request/send', 'RequestController@send')->name('request.send');

//Tariffs
Route::get('tariffs', 'TariffController@index')->name('tariffs');
Route::get('tariffs/models', 'TariffController@models')->name('tariffs.models');
Route::get('tariffs/car', 'TariffController@car')->name('tariffs.car');

//Services
Route::get('service/tariff', 'Services\\CarTariff@handle');
Route::get('dashboard', [IndexController::class, 'index']);


//Cities
Route::get('goroda', 'CityController@list')->name('cities.list');
Route::get('{city}', 'CityController@index')->name('city');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Orchid\Access\UserAccess;
use Orchid\Filters\Filterable;
use Orchid\Metrics\Chartable;
use Orchid\Screen\AsSource;
use Ramsey\Collection\Collection;

/**
 * Class Post
 * @package App
 * @property string $title
 * @property string $body
 * @property string $image
 * @property string $slug
 * @property array $related
 * @property string $meta_title
 * @property string $meta_description
 */
class Post extends Model
{

    use AsSource, UserAccess, AsSource, Filterable, Chartable;

    /**
     * @var string[]
     */
    protected $attributes = ['related' => '[]',];

    /**
     * @var string[]
     */
    protected $casts = [
        'title' => 'string',
        'body' => 'string',
        'image' => 'string',
        'slug' => 'string',
        'meta_title' => 'string',
        'meta_description' => 'string',
        'related' => 'array',
    ];

    /**
     * @var string[]
     */
    protected $fillable = [
        'title',
        'body',
        'image',
        'slug',
        'related',
        'meta_title',
        'meta_description',
        'created_at',
    ];

    /**
     * @var string[]
     */
    protected $allowedFilters = [
        'id',
        'title',
        'body',
        'slug',
        'created_at',
    ];

    /**
     * @var string[]
     */
    protected $allowedSorts = [
        'id',
        'title',
        'body',
        'slug',
        'created_at',
    ];

    /**
     * @return string
     */
    public function getShortBodyAttribute()
    {
        $text = $this->attributes['body'];
        $text = str_replace(['</p><p>', '</p>', '<p>'], ['', '', PHP_EOL], $text);
        $text = strip_tags($text);
        return mb_substr($text, 0, 400);
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        if (!Str::startsWith(request()->path(), 'dashboard'))
            return 'slug';
        return 'id';
    }

    /**
     * @return Collection<Post>
     */
    public function related()
    {
        return Post::find($this->related);
    }
}

resources/views/partials/body.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {!! SEO::generate() !!}
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body>
@include('partials.header')

@yield('content')

@include('partials.footer')

@stack('modals')

<jivoscript src="//code-ya.jivosite.com/widget/5EA4cwqwIS"></jivoscript>
<script src="{{ mix('js/app.js') }}"></script>
@stack('scripts')

<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(66540163, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
    });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/66540163" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>

resources/views/partials/bread.blade.php
<div class="breadcrumbs">
    @foreach(collect($crumbs) as $text => $link)
        <a href="{{ $link }}">{{ $text }}</a>
    @endforeach
</div>

resources/views/partials/car_tariff_result.blade.php
<h2>{{ __('page.tariff.calculator.result.title', compact('car')) }}</h2>
@foreach($tariffs as $tariff)
    <p>{!! __('page.tariff.calculator.result.tariff', ['tariff' => $tariff->name]) !!} {{ $tariff->tariff_requirements }}</p>
@endforeach
<a href="#" class="btn btn-dark" modal="modal_request">{{ __('page.header.left_request_connect') }}</a>

resources/views/partials/city.blade.php
<div class="col-md-4 city">
    <a href="{{ route('city', $city) }}">
        <img src="{{ $city->image }}" alt="{{ $city->name }}">
        <h2>{{ $city->name }}</h2>
    </a>
</div>

resources/views/partials/connect_block.blade.php
<section class="bg-primary">
    <div class="container py-5 block-connect">
        <p class="h2">{{ __('page.loops.connect.title') }}</p>
        <p class="description">{{ __('page.loops.connect.description') }}</p>
        <form action="{{ route('request.send') }}" method="POST" id="form-request-category">
            @csrf
            <input type="hidden" name="source" value="{{ $page_name ?? '' }}">
            <input type="hidden" name="ip" value="{{ request()->ip() ?? '' }}">
            <input type="text" name="name" placeholder="{{ __('page.loops.forms.name') }}" required>
            <input type="text" name="phone" placeholder="{{ __('page.loops.forms.phone') }}" required>
            <button type="submit" class="btn btn-dark">{{ __('page.header.left_request') }}</button>
        </form>
    </div>
</section>

resources/views/partials/footer.blade.php
<footer class="footer bg-dark py-5">
    <div class="container">
        <div class="row mb-25">
            <ul class="list-unstyled col-6 col-md-4">
                <li><a href="#">{{ __('page.header.links.auto') }}</a></li>
                <li><a href="#">{{ __('page.header.links.cities') }}</a></li>
                <li><a href="#">{{ __('page.header.links.articles') }}</a></li>
            </ul>
            <ul class="list-unstyled col-6 col-md-3">
                <li><a href="/#">{{ __('page.index.calculator.title') }}</a></li>
                <li><a href="/#">{{ __('page.index.questions.title') }}</a></li>
                <li><a href="#">{{ __('page.header.left_request') }}</a></li>
            </ul>
            <div class="col-md-5 offset-lg-2 col-lg-3 numbers">
                <div class="row">
                    <a href="tel:{{ __('page.header.phone_1_call') }}" class="col-6 col-md-12">{{ __('page.header.phone_1') }}</a>
                    <a href="tel:{{ __('page.header.phone_2_call') }}" class="col-6 col-md-12">{{ __('page.header.phone_2') }}</a>
                </div>
            </div>
        </div>
        <p class="copyright">{{ __('page.index.footer.copyright') }}</p>
    </div>
</footer>

@push('modals')
    <div class="modal-container" id="modal_thx">
        <div class="modal-background">
            <div class="modal">
                <p class="modal-title">{{ __('page.modal.thanks.title') }}</p>
                <p class="modal-comment">{{ __('page.modal.thanks.comment') }}</p>
                <svg width="150" height="150" viewBox="0 0 510 510" xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink">
                    <path
                        d="M150.45,206.55l-35.7,35.7L229.5,357l255-255l-35.7-35.7L229.5,285.6L150.45,206.55z M459,255c0,112.2-91.8,204-204,204 S51,367.2,51,255S142.8,51,255,51c20.4,0,38.25,2.55,56.1,7.65l40.801-40.8C321.3,7.65,288.15,0,255,0C114.75,0,0,114.75,0,255 s114.75,255,255,255s255-114.75,255-255H459z"></path>
                </svg>
            </div>
        </div>
    </div>
@endpush

@push('modals')
    <div class="modal-container modal-form" id="modal_request">
        <div class="modal-background">
            <div class="modal">
                <span class="close"></span>
                <p class="modal-title">{{ __('page.header.left_request') }}</p>
                <form action="{{ route('request.send') }}" method="POST" id="form-request-modal">
                    @csrf
                    <input type="hidden" name="source" value="Модальное окно: {{ request()->url() }}">
                    <input type="hidden" name="ip" value="{{ request()->ip() ?? '' }}">
                    <input type="text" name="name" placeholder="{{ __('page.loops.forms.name') }}" required>
                    <input type="text" name="phone" placeholder="{{ __('page.loops.forms.phone') }}" required>
                    <button type="submit" class="btn btn-primary">{{ __('page.header.left_request') }}</button>
                </form>
            </div>
        </div>
    </div>
@endpush

resources/views/partials/header.blade.php
<header class="container-fluid bg-dark" id="header">
    <nav class="container navbar navbar-expand-lg navbar-light">
        <div class="row">
            <a class="navbar-brand" href="/">{{ __('page.header.logo') }}</a>
            <button class="navbar-toggler d-inline-block d-md-none" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                @include('partials.icons.burger')
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link phone" href="tel:{{ __('page.header.phone_1_call') }}">{{ __('page.header.phone_1') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link phone hd" href="tel:{{ __('page.header.phone_2_call') }}">{{ __('page.header.phone_2') }}</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('tariffs') }}">{{ __('page.header.links.auto') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('cities.list') }}">{{ __('page.header.links.cities') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('posts.list') }}">{{ __('page.header.links.articles') }}</a>
                    </li>
                </ul>
            </div>
            <a href="#" class="btn btn-primary" modal="modal_request">{{ __('page.index.slide.button') }}</a>
        </div>
    </nav>
</header>

resources/views/partials/options.blade.php
@foreach($options as $key => $val)
    <option value="{{ $key }}">{{ $val }}</option>
@endforeach

resources/views/partials/post.blade.php
<a href="{{ route('post', $post) }}" class="card mb-25 post-small">
    <div class="col-12 col-sm-4 post-image">
        <img src="{{ $post->image }}" alt="{{ $post->title }}">
    </div>
    <div class="col-12 col-sm-8 post-content">
        <h3 class="post-title">{{ $post->title }}</h3>
        <p class="post-body">{!! $post->short_body !!}...</p>
        <span class="read-more">{{ __('page.posts.read_more') }}</span>
    </div>
</a>

resources/views/partials/post_related.blade.php
<a href="{{ route('post', $post) }}" class="card mb-25 post-related">
    <img src="{{ $post->image }}" alt="{{ $post->title }}">
    <div class="post-content">
        <p class="post-title">{{ $post->title }}</p>
        <span class="read-more">{{ __('page.posts.read_more') }}</span>
    </div>
</a>

resources/views/partials/range.blade.php
<ul class="range-labels">
    @foreach($items as $i => $item)
        <li class="{{ $i == ($value ?? 0) ? 'active selected' : '' }}">{{ $item }}</li>
    @endforeach
</ul>
<div class="range">
    <input type="range" min="0" max="{{ count($items) - 1 ?? 10 }}" steps="1" value="{{ $value ?? 0 }}" name="{{ $name ?? '' }}">
</div>